// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // The public flow is anon-only (create_confession + "reads approved only" are
    // granted to anon). Never let this client consume the magic-link token off the
    // /moderate redirect URL — that lives in ./moderation-client with its own
    // storageKey. Keeping this false prevents an admin session leaking into the
    // public confess/wall requests.
    detectSessionInUrl: false,
  }
});